### ISSUE TITLE
результати перевірки

### ISSUE THREAD

**Issue by Aqueelone** [salazart/sqltask#1]
Нижче наводятсья резщультати перевірки.
Коли з чимось не дуже згодні, наводбте свої контр аргументи, передивимося...

0. (SQL) 25 балів
1. (Palindrome) 20 балів + 10 оформлення + 10 гарний алгоритм + 10 гарні тести
3. (bigdata) 30 балів + 10 гарний алгоритм + 20 чудові тести
4. (cacheMap) 50 балів + 10 гарний алгоритм + 10 гарні тести
8. (social) 60 балів + 20 гарна реалізація + 20 гарна архітектура + 20 гарні тести
(Так як Ви не вказали який саме Ваш проект по соціальним мережам дивитися, оцінював по кращому на мій погляд... - по SocialNetwork)

**Comment by salazart** [comment]
Дякую, з усім згодний.
